name: Beyond The Ripples
favicon: null
layout_spectrum: 0.9455352218355983
typography_spectrum: 0.8412420612294227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.10144531191326678
  lightness: 0.8555300801526755
  saturation: 0.12405239790678024
  rhythmicContrast: 0.7976424493826926
purpose: []
